notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install pylint
  - pip install coveralls
  - pip install sphinx sphinx-rtd-theme
  - pip install .
script:
  - pylint parts
  - nosetests
  - cd docs && sphinx-apidoc -f -E --templatedir=_templates -o _source .. ../setup.py && make html
after_success:
  - coveralls
