name: build-publish
on:
  push
jobs:
  build:
    name: Build distribution package.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Python.
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install pypa/build.
      run: python -m pip install .[publish]
    - name: Build a source tarball and a binary wheel.
      run: python -m build --sdist --wheel .
    - name: Store the distribution packages.
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish:
    name: Publish distribution package to PyPI.
    if: startsWith(github.ref, 'refs/tags/') # Publish on tag pushes.
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/parts
    permissions:
      id-token: write
    steps:
    - name: Download all the distributions.
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution package to PyPI.
      uses: pypa/gh-action-pypi-publish@release/v1
